// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jamillosantos/migrations/v2 (interfaces: Source,Target,Migration,RunnerReporter)
//
// Generated by this command:
//
//	mockgen -package migrations -destination migration_mock_test.go github.com/jamillosantos/migrations/v2 Source,Target,Migration,RunnerReporter
//

// Package migrations is a generated GoMock package.
package migrations

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSource) Add(ctx context.Context, migration Migration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, migration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockSourceMockRecorder) Add(ctx, migration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSource)(nil).Add), ctx, migration)
}

// Load mocks base method.
func (m *MockSource) Load(ctx context.Context) (Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].(Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSourceMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSource)(nil).Load), ctx)
}

// MockTarget is a mock of Target interface.
type MockTarget struct {
	ctrl     *gomock.Controller
	recorder *MockTargetMockRecorder
	isgomock struct{}
}

// MockTargetMockRecorder is the mock recorder for MockTarget.
type MockTargetMockRecorder struct {
	mock *MockTarget
}

// NewMockTarget creates a new mock instance.
func NewMockTarget(ctrl *gomock.Controller) *MockTarget {
	mock := &MockTarget{ctrl: ctrl}
	mock.recorder = &MockTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTarget) EXPECT() *MockTargetMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTarget) Add(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTargetMockRecorder) Add(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTarget)(nil).Add), ctx, id)
}

// Create mocks base method.
func (m *MockTarget) Create(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTargetMockRecorder) Create(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTarget)(nil).Create), ctx)
}

// Current mocks base method.
func (m *MockTarget) Current(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockTargetMockRecorder) Current(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockTarget)(nil).Current), ctx)
}

// Destroy mocks base method.
func (m *MockTarget) Destroy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockTargetMockRecorder) Destroy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockTarget)(nil).Destroy), ctx)
}

// Done mocks base method.
func (m *MockTarget) Done(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Done indicates an expected call of Done.
func (mr *MockTargetMockRecorder) Done(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockTarget)(nil).Done), ctx)
}

// FinishMigration mocks base method.
func (m *MockTarget) FinishMigration(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishMigration", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishMigration indicates an expected call of FinishMigration.
func (mr *MockTargetMockRecorder) FinishMigration(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishMigration", reflect.TypeOf((*MockTarget)(nil).FinishMigration), ctx, id)
}

// Lock mocks base method.
func (m *MockTarget) Lock(ctx context.Context) (Unlocker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx)
	ret0, _ := ret[0].(Unlocker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockTargetMockRecorder) Lock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockTarget)(nil).Lock), ctx)
}

// Remove mocks base method.
func (m *MockTarget) Remove(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockTargetMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTarget)(nil).Remove), ctx, id)
}

// StartMigration mocks base method.
func (m *MockTarget) StartMigration(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMigration", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMigration indicates an expected call of StartMigration.
func (mr *MockTargetMockRecorder) StartMigration(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMigration", reflect.TypeOf((*MockTarget)(nil).StartMigration), ctx, id)
}

// MockMigration is a mock of Migration interface.
type MockMigration struct {
	ctrl     *gomock.Controller
	recorder *MockMigrationMockRecorder
	isgomock struct{}
}

// MockMigrationMockRecorder is the mock recorder for MockMigration.
type MockMigrationMockRecorder struct {
	mock *MockMigration
}

// NewMockMigration creates a new mock instance.
func NewMockMigration(ctrl *gomock.Controller) *MockMigration {
	mock := &MockMigration{ctrl: ctrl}
	mock.recorder = &MockMigrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigration) EXPECT() *MockMigrationMockRecorder {
	return m.recorder
}

// CanUndo mocks base method.
func (m *MockMigration) CanUndo() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUndo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanUndo indicates an expected call of CanUndo.
func (mr *MockMigrationMockRecorder) CanUndo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUndo", reflect.TypeOf((*MockMigration)(nil).CanUndo))
}

// Description mocks base method.
func (m *MockMigration) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockMigrationMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockMigration)(nil).Description))
}

// Do mocks base method.
func (m *MockMigration) Do(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockMigrationMockRecorder) Do(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockMigration)(nil).Do), ctx)
}

// ID mocks base method.
func (m *MockMigration) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockMigrationMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockMigration)(nil).ID))
}

// Next mocks base method.
func (m *MockMigration) Next() Migration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(Migration)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockMigrationMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockMigration)(nil).Next))
}

// Previous mocks base method.
func (m *MockMigration) Previous() Migration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Previous")
	ret0, _ := ret[0].(Migration)
	return ret0
}

// Previous indicates an expected call of Previous.
func (mr *MockMigrationMockRecorder) Previous() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Previous", reflect.TypeOf((*MockMigration)(nil).Previous))
}

// SetNext mocks base method.
func (m *MockMigration) SetNext(arg0 Migration) Migration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNext", arg0)
	ret0, _ := ret[0].(Migration)
	return ret0
}

// SetNext indicates an expected call of SetNext.
func (mr *MockMigrationMockRecorder) SetNext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNext", reflect.TypeOf((*MockMigration)(nil).SetNext), arg0)
}

// SetPrevious mocks base method.
func (m *MockMigration) SetPrevious(arg0 Migration) Migration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrevious", arg0)
	ret0, _ := ret[0].(Migration)
	return ret0
}

// SetPrevious indicates an expected call of SetPrevious.
func (mr *MockMigrationMockRecorder) SetPrevious(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrevious", reflect.TypeOf((*MockMigration)(nil).SetPrevious), arg0)
}

// String mocks base method.
func (m *MockMigration) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockMigrationMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockMigration)(nil).String))
}

// Undo mocks base method.
func (m *MockMigration) Undo(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undo", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undo indicates an expected call of Undo.
func (mr *MockMigrationMockRecorder) Undo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undo", reflect.TypeOf((*MockMigration)(nil).Undo), ctx)
}

// MockRunnerReporter is a mock of RunnerReporter interface.
type MockRunnerReporter struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerReporterMockRecorder
	isgomock struct{}
}

// MockRunnerReporterMockRecorder is the mock recorder for MockRunnerReporter.
type MockRunnerReporterMockRecorder struct {
	mock *MockRunnerReporter
}

// NewMockRunnerReporter creates a new mock instance.
func NewMockRunnerReporter(ctrl *gomock.Controller) *MockRunnerReporter {
	mock := &MockRunnerReporter{ctrl: ctrl}
	mock.recorder = &MockRunnerReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnerReporter) EXPECT() *MockRunnerReporterMockRecorder {
	return m.recorder
}

// AfterExecute mocks base method.
func (m *MockRunnerReporter) AfterExecute(ctx context.Context, info *AfterExecuteInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterExecute", ctx, info)
}

// AfterExecute indicates an expected call of AfterExecute.
func (mr *MockRunnerReporterMockRecorder) AfterExecute(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterExecute", reflect.TypeOf((*MockRunnerReporter)(nil).AfterExecute), ctx, info)
}

// AfterExecuteMigration mocks base method.
func (m *MockRunnerReporter) AfterExecuteMigration(ctx context.Context, info *AfterExecuteMigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterExecuteMigration", ctx, info)
}

// AfterExecuteMigration indicates an expected call of AfterExecuteMigration.
func (mr *MockRunnerReporterMockRecorder) AfterExecuteMigration(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterExecuteMigration", reflect.TypeOf((*MockRunnerReporter)(nil).AfterExecuteMigration), ctx, info)
}

// BeforeExecute mocks base method.
func (m *MockRunnerReporter) BeforeExecute(ctx context.Context, info *BeforeExecuteInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BeforeExecute", ctx, info)
}

// BeforeExecute indicates an expected call of BeforeExecute.
func (mr *MockRunnerReporterMockRecorder) BeforeExecute(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeExecute", reflect.TypeOf((*MockRunnerReporter)(nil).BeforeExecute), ctx, info)
}

// BeforeExecuteMigration mocks base method.
func (m *MockRunnerReporter) BeforeExecuteMigration(ctx context.Context, info *BeforeExecuteMigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BeforeExecuteMigration", ctx, info)
}

// BeforeExecuteMigration indicates an expected call of BeforeExecuteMigration.
func (mr *MockRunnerReporterMockRecorder) BeforeExecuteMigration(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeExecuteMigration", reflect.TypeOf((*MockRunnerReporter)(nil).BeforeExecuteMigration), ctx, info)
}
